backend:
  name: git-gateway
  branch: admin-test

media_folder: "src/assets/img/media"
public_folder: "/assets/img/media"
publish_mode: editorial_workflow

collections:
  - name: "episodios" # Used in routes, e.g., /admin/collections/blog
    label: "Episódios" # Used in the UI
    folder: "src/pages/ux-research/camila-borja-pt2/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: title
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      # - {label: "Publish Date", name: "date", widget: "datetime"}
      # - {label: "Featured Image", name: "thumbnail", widget: "image"}
      # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      # - {label: "Body", name: "body", widget: "markdown"}